### ISSUE TITLE
ID type mismatch with wiz_combine()

### ISSUE THREAD

**Issue by carajoycebiostats** [ML4LHS/wizard#1]
I have a long unique identifier for my hospital encounter ID (maximum 12 byte integer).  This causes problems in wiz_combine (below).  I've tried setting both IDs to be of the same format going in to wiz_frame() and wiz_add_predictors() with no luck.  

Error: Can't join on `x$encounter_id` x `y$encounter_id` because of incompatible types.
`x$encounter_id` is of type <double>>.
`y$encounter_id` is of type <integer64>>.

**Comment by kdpsingh** [comment]
Thanks @carajoycebiostats for reporting this! When you say that you tried to set them to the same type before sending to wiz_frame(), did you try setting them both to character types with as.character()?

I have a feeling this has to do with the use of data.table::fwrite() and data.table::fread() which may not be able to distinguish between character IDs and numeric (as it tries to auto-detect type). If so, this should be fixable. Will try to recreate this on our end.

**Comment by carajoycebiostats** [comment]
Thanks @kdpsingh! I will try as.character().  Was hoping to avoid converting all over since my many temporal datasets are quite long and all as.double() currently.  I tried as.integer64() since that was what was returned with the error message - sorry for bad copy/paste above, it should say
x$encounter_id is of type double.
y$encounter_id is of type integer64.

**Comment by kdpsingh** [comment]
Ah, that makes more sense. My guess is that the error is coming from dplyr::inner_join(), which is how wiz_combine() joins datasets by default. inner_join() is probably throwing the error after seeing different data types for the identifiers.

Did converting all identifiers to as.double() fix the problem?

If you don't want to fix this problem by hand for each dataset individually, you could potentially replace the dplyr::inner_join() function with a custom function since wiz_combine() lets you override the default join function with its argument `dplyr_join`.

**Comment by kdpsingh** [comment]
I will close this issue for now @carajoycebiostats but let me know if harmonizing the data types doesn't fix the problem and I will re-open.
